"""second

Revision ID: 40a1f09e4e34
Revises: 699e4a6c38cc
Create Date: 2022-10-18 15:02:46.670031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a1f09e4e34'
down_revision = '699e4a6c38cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'name')
    # ### end Alembic commands ###
